### ISSUE TITLE
DMP-A8 bugs

### ISSUE THREAD

**Issue by arachnida** [hchris1/Eversolo#109]
### Describe the issue

Hi,
first of all thanks for writing this HA add-on!

I'm testing your project against a DMP-A8 running the latest FW v1.3.80. HA is running on a RPi5 with NVMe SSD. HACS doesn't find the project but manual install went fine.
Here are some bugs I found:
-Eversolo display button: it dims the display to 0%, but doesn't switch it off. (0% is quite dim but visible)
-Eversolo knob: Switches off the light but when switching on it is set at 100%, it doesn't retain the previous setting.

The player tile on HA seems to work fine, reacts quite fast and the album art is displayed. I only find the fade out on the left side of the album art a bit too much.

Please do not hesitate to contact me for more testing, glad to help.

### Reproduction steps

1. Manual install
2. Toggle Eversolo Display button
3. Toggle Eversolo Knob button
...

**Comment by hchris1** [comment]
Hi @arachnida,

Thanks for reporting this, and apologies for the delayed response!

Regarding the issues you mentioned:
- **Light display entity**: I found a hacky workaround to detect if the display is fully off, which allowed me to integrate the toggle display on/off command. The behavior seems consistent with a normal light, so you can now use the on/off button on the display light entity to fully turn off the display or restore it to the last brightness.
- **Light knob entity**: Unfortunately, Eversolo doesn’t provide a way to turn off the knob and automatically return to the last brightness. The knob and display behave differently, but I’ve added functionality to save the last brightness so it restores when turned back on. Hopefully, this improves things!
- **Album art**: The album art from the Eversolo comes whithout a fade on the left side. There is no manipulation of the album art within the integration. I would assume that your Home Assistant card applies this fade to make it look nicer (?).

The changes I mentioned are available in the newest update (0.4.4). Let me know what you think :)

Cheers,
Christian

**Comment by arachnida** [comment]
Hi Christian,

thanks for your response and I didn't mind the delay, there is another life outside Github!

-The large display now get switched off completely, bug squashed.
-The Knob workaround also works now if controlled using HA and the iOS app, when I use the slider in the app the entity in HA also changes accordingly, certainly an improvement and great work! The sync isn't perfect, but at least when controlled from HA it works now. It sometimes messes up when using both the HA and iOS app control at the same time but I guess this is expected behaviour until the Eversolo API gives you more control.
-Regarding the album art fade this seems indeed to be the media control card adding a fade on the left side as the smaller control panel doesn't show the fade in the small album cover. Is it possible to extract the album art as a separate image file, would be nice to show the file full size on my HA screen?

Cheers, thanks and have a great 2025,
Ivo

**Comment by hchris1** [comment]
Hi @arachnida,

the desync of the last knob brightness level when using iOS and the HA integration is currently expected. Maybe I can bring some improvements for that in the future.

Regarding the album art: There are some possibilities to display this separately on your dashboard:
1. **Mini Media Player**: If you want to play around with card-mod, you can try and customize an existing media player tile ([Scrolling through this thread might help](https://community.home-assistant.io/t/lovelace-mini-media-player/68459/3122)). This will probably take some time to figure it out.
2. **Generic Camera**: If you want a somewhat easier solution, you can register a generic camera which shows the current artwork. I just tried it, so here you go:
    - Go to devices and integrations
    - Add a new integration
    - Search for generic camera and select it
    - Enter the following for the still image URL: https://Your_HA{{ state_attr('media_player.eversolo', 'entity_picture') }}
      - **Your_HA** can be a domain if you have set up to use Home Assistant from external as well, or just an IP address. Note that this is the address of your Home Assistant server, **not** your Eversolo device. **Your_HA** could be **192.168.178.2:8123** or **your_ha_instance.com** as an example.
      - Make sure to change **media_player.eversolo** to something else in case your Eversolo media player instance is named differently.
    - You should then get a generic camera entity that shows the album art that you can integrate in your dashboard


I hope this helps! In case you like the integration so far, I would appreciate giving it a star or even [buying me a coffee](https://buymeacoffee.com/hchris1) :)

Cheers,
Christian

**Comment by arachnida** [comment]
Hi Christian,

thanks for the tip about the album art picture. The Generic Camera picture however didn't refresh unless clicked the tile (maybe a misconfiguration?) so I used the picture entity to inject it into "Refreshable Picture" I found in HACS. This works great and gives me a nice big album art picture!

Ciao,
arachnida
