### ISSUE TITLE
Ability to show and set outputs state

### ISSUE THREAD

**Issue by therobster121** [hchris1/Eversolo#25]
### Is your feature request related to a problem? Please describe.

 When I listen to music on my eversolo I like to switch the output to USB so it is fed into my DAC.
after I switch back to XLR which is used to listen to TV (input is then optical).

There doesn't appear to be an entity/attribute that allows be to view, set and display output state.

At the moment I am doing this with a rest call:
http://<IP address>/ZidooMusicControl/v2/setOutInputList?tag=USB

For TV I switch back to XLR
http://<IP address>/ZidooMusicControl/v2/setOutInputList?tag=XLR

### Describe the solution you'd like

I would like an an entity / attribute that can show and set outputs (tag).  Similar to inputs for source.
The attribute may already exist. If so I can't find it.

### Describe alternatives you've considered

At the moment I am doing this with a rest call:
http://<IP address>/ZidooMusicControl/v2/setOutInputList?tag=USB

For TV I switch back to XLR
http://<IP address>/ZidooMusicControl/v2/setOutInputList?tag=XLR

problem with this approach is the state is not reflected in the mediaplayer or other HA entity.

### Additional context

I'm using a combination of inputs and outputs to control input from internal player and TV (via optical)
when using internal player and listening to my on music I like to switch output to DAC.

Having the ability to control both inputs and outputs would mean I can setup all scenario's as 1 button automations.

**Comment by therobster121** [comment]
Perhaps this could be added to mediaplayer  "select_sound_mode"? appears to be the only option for managing outputs in mediaplayer?
otherwise could be managed similar VUmeter

**Comment by hchris1** [comment]
Hi @therobster121! Thank you for the request. I will integrate this. I can't tell you exactly when but I'll try and do it as soon as I find some time.

**Comment by therobster121** [comment]
Hi Chris,

Let me know if you need any assistance with testing etc. I know python but
have close to 0 HA experience. If. I can help I will.

**Comment by hchris1** [comment]
Sorry, didn't want to close the issue straight away. It was automatically done because of the pull request.

**Comment by hchris1** [comment]
@therobster121 Check out the new update! There is an output selector available. I didn't use `select_sound_mode` because it seemed like it's not as easy to operate from the UI.

Let me know if it works for you!

**Comment by therobster121** [comment]
Hi Chris,

Wow fast turnaround!!!
I tested this on my DMP-A06 and it works well.

sorry about closing the ticket. I forked the repo so I could understand how
the integration works and tinker.

Rob

**Comment by hchris1** [comment]
@therobster121 Nice! The integration could need some refactoring at some places but well... I'll work on that when I have some more time.

In case you like the integration and you want to help me out: https://www.buymeacoffee.com/hchris1

Cheers
Chris
