### ISSUE TITLE
Input selection

### ISSUE THREAD

**Issue by hanvanvilsteren** [hchris1/Eversolo#32]
### Is your feature request related to a problem? Please describe.

I think the input selection needs to be added because it is a very important requirement to enable important automations. 

### Describe the solution you'd like

I'm not a programmer but I found specific HTML code to switch to different inputs. (Behind fetch, and '+DMPA6IP+' needs to be replaced with the IP address. Pasting the commands (in additional text) in the browser switches the inputs. Hope this can help you to add also the input_control to the integration!

### Describe alternatives you've considered

Found the Paste URL's on this forum:
https://www.audiosciencereview.com/forum/index.php?threads/eversolo-dmp-diy-web-control-panel-v1-0.50261/

Download the zip file, in Eversolo.html you can find maybe other Paste URL's. 

### Additional context

									<IMG SRC="icons_white/icon_player.png" width=60 height=60><BR><BR>
									<button type="submit" onClick="fetch('http://'+DMPA6IP+':9529/ZidooMusicControl/v2/setInputList?tag=XMOS&index=0')">PLAYER</button>
								</TD>
								<TD width="20%" valign=middle align=center>
									<IMG SRC="icons_white/icon_bt.png" width=60 height=60><BR><BR>
									<button type="submit" onClick="fetch('http://'+DMPA6IP+':9529/ZidooMusicControl/v2/setInputList?tag=BT&index=1')">BLUETOOTH</button>
								</TD>
								<TD width="20%" valign=middle align=center>
									<IMG SRC="icons_white/icon_usb.png" width=60 height=60><BR><BR>
									<button type="submit" onClick="fetch('http://'+DMPA6IP+':9529/ZidooMusicControl/v2/setInputList?tag=USB&index=2')">USB-C</button>
								</TD>
								<TD width="20%" valign=middle align=center>
									<IMG SRC="icons_white/icon_toslink.png" width=60 height=60><BR><BR>
									<button type="submit" onClick="fetch('http://'+DMPA6IP+':9529/ZidooMusicControl/v2/setInputList?tag=SPDIF&index=3')">OPTICAL</button>
								</TD>
								<TD width="20%" valign=middle align=center>
									<IMG SRC="icons_white/icon_coax.png" width=60 height=60><BR><BR>
									<button type="submit" onClick="fetch('http://'+DMPA6IP+':9529/ZidooMusicControl/v2/setInputList?tag=RCA&index=4')">COAXIAL</button>

**Comment by hchris1** [comment]
@hanvanvilsteren Hi there! Seems like you already found this feature in the integration in the media player entity.

Let me know in case you encounter any issues with the input selection. Also feel free to give the repo a star in case you like it :)

**Comment by hanvanvilsteren** [comment]
Indeed! I found the option. There is however, if you select the integration an GUI control applet (selector) for vu-meters and the output. There is no gui selector for inputs. Not a big deal for me because I use it now for automation my spdif input when home assistant sees my TV becoming online. Very helpful ty!Maybe its a handy option to add also the input selector directly in the GUI as an option.Cheers HanOp 19 jan 2024 om 16:33 heeft Christian Horn ***@***.***> het volgende geschreven:﻿
@hanvanvilsteren Hi there! Seems like you already found this feature in the integration in the media player entity.
Let me know in case you encounter any issues with the input selection. Also feel free to give the repo a star in case you like it :)

**Comment by hchris1** [comment]
The reason I didn't do that is because it felt somewhat against the Home Assistant philosophy because the media player entity already has support for source selection. I will consider this feedback!

Glad you find the integration useful :)
Chris

**Comment by hanvanvilsteren** [comment]
No problem, maybe you should mention this in the readme of the integration. I’m not familiar with the media player in particular. I just found your integration because I was searching “eversolo home assistant” to create an automation automatically select the right input when tv becomes online. When it is turned off it selects the default input. That is for me quite an achievement lol.Have a good weekend.Cheers HanOp 19 jan 2024 om 16:59 heeft Christian Horn ***@***.***> het volgende geschreven:﻿
The reason I didn't do that is because it felt somewhat against the Home Assistant philosophy because the media player entity already has support for source selection. I will consider this feedback!
Glad you find the integration useful :)
Chris
