### ISSUE TITLE
add spectrum support

### ISSUE THREAD

**Issue by glc650** [hchris1/Eversolo#39]
### Is your feature request related to a problem? Please describe.

Any plans to add support for the spectrum mode of the A6?  Maybe a drop down menu (like VU Style) for setting the spectrum option and then a way to turn it on and cycle through the different spectrum related views  (the function button does this on the stock remote)?

### Describe the solution you'd like

n/a

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by hchris1** [comment]
@glc650 Thank you for the request!
I will check what I can do. Unfortunately, I won't have time until the weekend so it will take a couple of days.
Chris

**Comment by glc650** [comment]
No worries.  Thanks for just responding and looking into it.

**Comment by hchris1** [comment]
@glc650 Check out update [v0.4.0 🎉](https://github.com/hchris1/Eversolo/releases/tag/0.4.0)!

This adds 2 entities:
- Cycle screen mode (Spectrum) as a button entity
- Spectrum mode as a select entity

Unfortunately the API doesn't provide a more elegant for combining the VU screen cycle and Spectrum screen cycle. That's the best I can provide right now. Let me know if it works as expected.

In case you like the integration, you star it and/or buy me a coffee: https://www.buymeacoffee.com/hchris1

Chris

**Comment by glc650** [comment]
Works good thanks.

They are supposed to be improving the API.  Hopefully when that happens you will have more to work with.

**Comment by hchris1** [comment]
Thank you for your feedback. I'll close the issue :)
