### ISSUE TITLE
Power on from Home-Assistant

### ISSUE THREAD

**Issue by hostrup** [hchris1/Eversolo#95]
### Is your feature request related to a problem? Please describe.

I am using the intrgration with the DMP-A8. 
It works nice - and i primarily use it to turn on my Mono amps - when the amp is powered on. 

### Describe the solution you'd like

Could it somehow be possible to turn the unit on from the Mediaplayer? 
I now i can use WOL - but why not build it into the mediaplayer? 

### Describe alternatives you've considered

WOL switch :) 

### Additional context

Not much more than that.

**Comment by hchris1** [comment]
Hi @hostrup,

I tried implementing that but didn't manage to do so. The API used in this integration is entirely unavailable when the device is turned off.

Does the Eversolo app offer this feature? If so, we can find out how they do it 

I use the setting to turn on the device when the power is back on. I have some automations that turn power on and turn off the Eversolo and afterwards the power. Maybe you can use the available/unavailable info from the media player to turn other devices on/off.

Chris

**Comment by hostrup** [comment]
Hi Chris! 
Yes i saw that the API seems totally unavailable when the device is in standby. 
But i found out that simply by sending a wake-on-lan packet to the IP - will wake i up. 
So i created a WOL sensor i HA - that i can use to turn it on. 

I remember that i did something like this back when i had my LG tv: 

media_player:
  - platform: webostv
    host: IP_removed
    name: TV
    timeout: 5
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: hi-dd-en-ma-c0

Because turning it off works like a charm :).

**Comment by hchris1** [comment]
Sorry for replying late. So the behavior that you'd like to see is that the integrations sends a magic packet when pressing the turn on button, right?

**Comment by hostrup** [comment]
Hi! i just created a simple switch - and that works nice. i think i might look into creating a new mediaplayer as a template - and then use that switch as on / off - then i can use the "player control" to turn it on and off. 

Everything else works wonders.

**Comment by hchris1** [comment]
Closing because WOL power on won't be implemented for now.
