### ISSUE TITLE
Eversolo Playing information in HA

### ISSUE THREAD

**Issue by jaerc** [hchris1/Eversolo#99]
### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

I'm using this HA integration with my Eversolo DMP-A8 which works fine.
Is it possible to integrate information during playing? e.g. what will be currently played? Playing information and the picture regarding played title?

### Describe alternatives you've considered

none

### Additional context

none

**Comment by jaerc** [comment]
Hi Christian,

I did found this screen under entities, but I don’t know how to add this to the dashboard. In config mode (please see screenshot) I do not have this entity to add it to the dashboard, and within media player entities I have no option to add this function to the dashboard.

What I’m doing wrong?

Many thanks for your help,

Chris


Von: Christian Horn ***@***.***>
Gesendet: Samstag, 9. November 2024 15:30
An: hchris1/Eversolo ***@***.***>
Cc: jaerc ***@***.***>; Mention ***@***.***>
Betreff: Re: [hchris1/Eversolo] Eversolo Playing information in HA (Issue #99)


Hi @jaerc<https://github.com/jaerc>,

I have implemented this feature but only tested it using the Eversolo DMP-A6. The integration should show current title, picture,... within the media player entity. Did you have a look there?
image.png (view on web)<https://github.com/user-attachments/assets/528c7a9f-a8cc-415f-847e-bcf0abcee3c0>

**Comment by jaerc** [comment]
Hi Christian,

Sorry for confusing, I was able to add this entity now to the dashboard, but I cannot se the picture. (See screenshot).
I play music from quobuz and I get the picture on the DMP-A8 screen and as well in the eversolo app.

Regards,
Chris


Von: Chris ...
Gesendet: Samstag, 9. November 2024 15:57
An: hchris1/Eversolo ***@***.***>; hchris1/Eversolo ***@***.***>
Cc: Mention ***@***.***>
Betreff: AW: [hchris1/Eversolo] Eversolo Playing information in HA (Issue #99)

Hi Christian,

I did found this screen under entities, but I don’t know how to add this to the dashboard. In config mode (please see screenshot) I do not have this entity to add it to the dashboard, and within media player entities I have no option to add this function to the dashboard.

What I’m doing wrong?

Many thanks for your help,

Chris


Von: Christian Horn ***@***.******@***.***>>
Gesendet: Samstag, 9. November 2024 15:30
An: hchris1/Eversolo ***@***.******@***.***>>
Cc: jaerc ***@***.******@***.***>>; Mention ***@***.******@***.***>>
Betreff: Re: [hchris1/Eversolo] Eversolo Playing information in HA (Issue #99)


Hi @jaerc<https://github.com/jaerc>,

I have implemented this feature but only tested it using the Eversolo DMP-A6. The integration should show current title, picture,... within the media player entity. Did you have a look there?
image.png (view on web)<https://github.com/user-attachments/assets/528c7a9f-a8cc-415f-847e-bcf0abcee3c0>

**Comment by hchris1** [comment]
I see. I'll have to check out quobuz. The Eversolo API is kind of strange when providing the currently played song. The data structures vary depending on playback source.

**Comment by jaerc** [comment]
Hi Christian,

I also did check with audio files on the internal harddisk and also with the internat radio player app.
I never get a picture wit the eversolo DMP-A8

Hope this helps

Von: Christian Horn ***@***.***>
Gesendet: Samstag, 9. November 2024 17:50
An: hchris1/Eversolo ***@***.***>
Cc: jaerc ***@***.***>; Mention ***@***.***>
Betreff: Re: [hchris1/Eversolo] Eversolo Playing information in HA (Issue #99)


I see. I'll have to check out quobuz. The Eversolo API is kind of strange when providing the currently played song. The data structures vary depending on playback source.

**Comment by hchris1** [comment]
Hi @jaerc,

it's a bit worrying that you don't see any image for audio files on the internal harddisk.

Can you try version 0.4.1 that I just released? I fixed the Qobuz album art issue by using the `albumArt` property that Eversolo introduced. Hopefully this fixes your issues.

Unfortunately, I have no access to a DMP-A8 :/

**Comment by hchris1** [comment]
Hi @jaerc,

glad to hear that! Hopefully Eversolo keeps the A-6 and A-8 interfaces identical.

If you'd like to support the project, there is a buy me a coffee link (https://buymeacoffee.com/hchris1). This is completely optional of course :)

**Comment by hchris1** [comment]
Closing because it seems to be resolved.
